In [96]:
import pandas as pd

## Primer dataset - Beneficiarios FONASA 2023

In [97]:
original1 = False
try:
    with open("../data/originales/Beneficiarios Fonasa 2023.csv", encoding="latin1", errors="ignore") as f:
        df_beneficiarios = pd.read_csv(f, nrows=1000000)
        print("Se cargo la muestra original")
        original1 = True
        # De tener dataset original, indica numero de filas a cargar o quitar nrows para carga completa

except FileNotFoundError:
    print("El archivo original no se encuentra, abriremos muestra") # Muestra de 100000 filas, habilitado para subir a github
    df_beneficiarios = pd.read_csv("../data/sample/beneficiarios_sample.csv", encoding='latin1')
    print("Se cargo la muestra")

Se cargo la muestra original

In [98]:
df_beneficiarios

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,202312,73025460,Mujer,60 a 69 años,Titular,B,500.001 - 550.000,Chilena,Dependiente,Trabajador Dependiente,Del Maule,Talca
999996,202312,69309925,Hombre,60 a 69 años,Titular,B,400.001 - 450.000,Chilena,Desempleado Con Seguro De Desempleo,Trabajador Dependiente,Del Maule,Yerbas Buenas
999997,202312,81914415,Hombre,60 a 69 años,Titular,B,1 - 100.000,Chilena,Dependiente,Trabajador Dependiente,Del Maule,Talca
999998,202312,76690915,Mujer,60 a 69 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,De Antofagasta,Antofagasta
999999,202312,68537515,Mujer,60 a 69 años,Carga,D,150.001 - 200.000,Chilena,Dependiente,Trabajador Dependiente,De Valparaíso,El Quisco

In [99]:
#revisar si tiene valores nulos
df_beneficiarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   MES_INFORMACION      1000000 non-null  int64
 1   CÓDIGO_BENEFICIARIO  1000000 non-null  int64
 2   SEXO                 1000000 non-null  object
 3   EDAD_TRAMO           1000000 non-null  object
 4   TITULAR_CARGA        1000000 non-null  object
 5   TRAMO_FONASA         1000000 non-null  object
 6   TRAMO_RENTA          1000000 non-null  object
 7   NACIONALIDAD         1000000 non-null  object
 8   CARACTERIZACIÓN      1000000 non-null  object
 9   TIPO_ASEGURADO       1000000 non-null  object
 10  REGIÓN_BENEFICIARIO  1000000 non-null  object
 11  COMUNA_BENEFICIARIO  1000000 non-null  object
dtypes: int64(2), object(10)
memory usage: 91.6+ MB

In [100]:
#eliminar las filas con valores nulos
df_beneficiarios_sin_nulos= df_beneficiarios.dropna()
df_beneficiarios_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   MES_INFORMACION      1000000 non-null  int64
 1   CÓDIGO_BENEFICIARIO  1000000 non-null  int64
 2   SEXO                 1000000 non-null  object
 3   EDAD_TRAMO           1000000 non-null  object
 4   TITULAR_CARGA        1000000 non-null  object
 5   TRAMO_FONASA         1000000 non-null  object
 6   TRAMO_RENTA          1000000 non-null  object
 7   NACIONALIDAD         1000000 non-null  object
 8   CARACTERIZACIÓN      1000000 non-null  object
 9   TIPO_ASEGURADO       1000000 non-null  object
 10  REGIÓN_BENEFICIARIO  1000000 non-null  object
 11  COMUNA_BENEFICIARIO  1000000 non-null  object
dtypes: int64(2), object(10)
memory usage: 91.6+ MB

In [101]:
#verificar si existen valores duplicados
df_beneficiarios_sin_nulos.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [102]:
#eliminar las filas duplicadas
df_beneficiarios_limpio = df_beneficiarios_sin_nulos.drop_duplicates()
df_beneficiarios_limpio.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 1000000, dtype: bool

In [103]:
df_beneficiarios_limpio

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
999995,202312,73025460,Mujer,60 a 69 años,Titular,B,500.001 - 550.000,Chilena,Dependiente,Trabajador Dependiente,Del Maule,Talca
999996,202312,69309925,Hombre,60 a 69 años,Titular,B,400.001 - 450.000,Chilena,Desempleado Con Seguro De Desempleo,Trabajador Dependiente,Del Maule,Yerbas Buenas
999997,202312,81914415,Hombre,60 a 69 años,Titular,B,1 - 100.000,Chilena,Dependiente,Trabajador Dependiente,Del Maule,Talca
999998,202312,76690915,Mujer,60 a 69 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,De Antofagasta,Antofagasta
999999,202312,68537515,Mujer,60 a 69 años,Carga,D,150.001 - 200.000,Chilena,Dependiente,Trabajador Dependiente,De Valparaíso,El Quisco

In [104]:
#guardaremos el dataframe limpio en un archivo csv
if original1 == True:
    df_beneficiarios_limpio.to_csv("../data/beneficiarios_original_limpio.csv", encoding='latin1', index=False)
elif original1 == False:
    df_beneficiarios_limpio.to_csv("../data/sample/beneficiarios_sample_limpio.csv", encoding='latin1', index=False)

## Segundo dataset - Modalidad Libre Elección 2023

In [105]:
original2 = False
try:
    with open("../data/originales/export MLE 2023.csv", encoding="latin1", errors="ignore") as f:
        df_MLE = pd.read_csv(f, nrows=1000000)
        print("Se cargo la muestra original")
        original2 = True
        # De tener dataset original, indica numero de filas a cargar o quitar nrows para carga completa

except FileNotFoundError:
    print("El archivo original no se encuentra, abriremos muestra") # Muestra de 100000 filas, habilitado para subir a github
    df_MLE = pd.read_csv("../data/sample/mle_2023_sample.csv", encoding="latin1")
    print("Se cargo la muestra")

Se cargo la muestra original

In [106]:
df_MLE.shape

(1000000, 13)

In [107]:
df_MLE

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTRACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,202308,101301,Atención Médica,Consulta Médica,82181868,B,60 a 64 años,Hombre,Metropolitana De Santiago,San Bernardo,1.0,10510,7010
999996,202308,101301,Atención Médica,Consulta Médica,69072699,C,60 a 64 años,Mujer,De Tarapacá,Iquique,1.0,10510,7010
999997,202308,101308,Atención Médica,Consulta Médica,75587862,D,30 a 34 años,Mujer,De Los Lagos,Osorno,1.0,10510,7010
999998,202308,101308,Atención Médica,Consulta Médica,85032515,B,30 a 34 años,Mujer,Metropolitana De Santiago,Santiago,1.0,10510,7010
999999,202308,101308,Atención Médica,Consulta Médica,75861667,B,30 a 34 años,Mujer,Metropolitana De Santiago,La Florida,1.0,10510,7010

In [108]:
df_MLE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   MES_EMISION          1000000 non-null  int64
 1   CODIGO_PRESTACIÓN    1000000 non-null  int64
 2   DESC_SECCION         1000000 non-null  object
 3   DESC_ITEM            1000000 non-null  object
 4   CODIGO_BENEFICIARIO  1000000 non-null  int64
 5   TRAMO_FONASA         999999 non-null   object
 6   EDAD_TRAMO           999999 non-null   object
 7   SEXO                 999999 non-null   object
 8   REGION_EMISION       999999 non-null   object
 9   COMUNA_EMISION       999999 non-null   object
 10  PRESTRACIONES        997531 non-null   float64
 11  MONTO_FAM            1000000 non-null  int64
 12  MONTO_COPAGO         1000000 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 99.2+ MB

In [109]:
#revisar si tiene valores nulos
df_MLE.isnull().values.any()

np.True_

In [110]:
# ver cuantos valores nulos hay por columna
df_MLE.isnull().sum()

MES_EMISION               0
CODIGO_PRESTACIÓN         0
DESC_SECCION              0
DESC_ITEM                 0
CODIGO_BENEFICIARIO       0
TRAMO_FONASA              1
EDAD_TRAMO                1
SEXO                      1
REGION_EMISION            1
COMUNA_EMISION            1
PRESTRACIONES          2469
MONTO_FAM                 0
MONTO_COPAGO              0
dtype: int64

In [111]:
#eliminar las filas con valores nulos
df_MLE_sin_nulos= df_MLE.dropna()
df_MLE_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 997529 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   MES_EMISION          997529 non-null  int64
 1   CODIGO_PRESTACIÓN    997529 non-null  int64
 2   DESC_SECCION         997529 non-null  object
 3   DESC_ITEM            997529 non-null  object
 4   CODIGO_BENEFICIARIO  997529 non-null  int64
 5   TRAMO_FONASA         997529 non-null  object
 6   EDAD_TRAMO           997529 non-null  object
 7   SEXO                 997529 non-null  object
 8   REGION_EMISION       997529 non-null  object
 9   COMUNA_EMISION       997529 non-null  object
 10  PRESTRACIONES        997529 non-null  float64
 11  MONTO_FAM            997529 non-null  int64
 12  MONTO_COPAGO         997529 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 106.5+ MB

In [112]:
#reviasr si existen valores duplicados
df_MLE_sin_nulos.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 997529, dtype: bool

In [113]:
# eliminar las filas duplicadas
df_MLE_limpio = df_MLE_sin_nulos.drop_duplicates()
df_MLE_limpio.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
999995    False
999996    False
999997    False
999998    False
999999    False
Length: 997529, dtype: bool

In [114]:
df_MLE_limpio = df_MLE_limpio.rename(columns={'PRESTRACIONES': 'PRESTACIONES'})

In [115]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,202308,101301,Atención Médica,Consulta Médica,82181868,B,60 a 64 años,Hombre,Metropolitana De Santiago,San Bernardo,1.0,10510,7010
999996,202308,101301,Atención Médica,Consulta Médica,69072699,C,60 a 64 años,Mujer,De Tarapacá,Iquique,1.0,10510,7010
999997,202308,101308,Atención Médica,Consulta Médica,75587862,D,30 a 34 años,Mujer,De Los Lagos,Osorno,1.0,10510,7010
999998,202308,101308,Atención Médica,Consulta Médica,85032515,B,30 a 34 años,Mujer,Metropolitana De Santiago,Santiago,1.0,10510,7010
999999,202308,101308,Atención Médica,Consulta Médica,75861667,B,30 a 34 años,Mujer,Metropolitana De Santiago,La Florida,1.0,10510,7010

In [116]:
#guardaremos el dataframe limpio en un archivo csv
if original2 == True:
    df_MLE_limpio.to_csv("../data/MLE_2023_original_limpio.csv", encoding='latin1', index=False)
elif original2 == False:
    df_MLE_limpio.to_csv("../data/sample/MLE_2023_sample_limpio.csv", encoding='latin1', index=False)

## Tercer Dataframe - Presupuestos MLE 2023

In [117]:
codigos_df = pd.read_excel("../data/originales/2 Planilla MLE 2023.xlsx", engine='openpyxl')

In [118]:
# Eliminamos codigos repetidos
codigos_df = codigos_df[~codigos_df["total1"].isin([0])].copy()

# Formateamos codigos a GSSPPP
codigos_df["CODIGO_PRESTACIÓN"] = (
    codigos_df['grupo'].astype(str).str.zfill(1) +
    codigos_df['sub_grupo'].astype(str).str.zfill(2) +
    codigos_df['presta'].astype(str).str.zfill(3)
)
codigos_df = codigos_df.rename(columns={"glosa": "NOMBRE_PRESTACIÓN"})

nombre_codigos = codigos_df[["CODIGO_PRESTACIÓN", "NOMBRE_PRESTACIÓN"]]

In [119]:
print(nombre_codigos['CODIGO_PRESTACIÓN'].duplicated().sum())

0

In [120]:
codigos_df.sample(5)

,secuencia,grupo,sub_grupo,presta,corr,titulo,anes1,anesben1,anes2,anesben2,...,valcir21,valcir22,valcir23,valcir31,valcir32,valcir33,valcir41,valcir42,valcir43,CODIGO_PRESTACIÓN
2208,2209,15,2,12,0,5,0,0,0,0,...,28518,37074,45628,0,0,0,0,0,0,1502012
35,36,1,1,205,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,101205
1519,1520,11,1,34,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1101034
663,664,3,6,54,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,306054
2373,2374,16,2,214,0,5,0,0,0,0,...,19574,25446,31318,0,0,0,0,0,0,1602214

In [121]:
codigos_df.to_csv("../data/Presupuestos_MLE_2023_original_limpio.csv", encoding='latin1', index=False)

**Hacemos merge df_MLE_limpio y nombre_codigos; y añadimos columna "NOMRE_PRESTACION" al df_MLE_limpio**

In [122]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,202308,101301,Atención Médica,Consulta Médica,82181868,B,60 a 64 años,Hombre,Metropolitana De Santiago,San Bernardo,1.0,10510,7010
999996,202308,101301,Atención Médica,Consulta Médica,69072699,C,60 a 64 años,Mujer,De Tarapacá,Iquique,1.0,10510,7010
999997,202308,101308,Atención Médica,Consulta Médica,75587862,D,30 a 34 años,Mujer,De Los Lagos,Osorno,1.0,10510,7010
999998,202308,101308,Atención Médica,Consulta Médica,85032515,B,30 a 34 años,Mujer,Metropolitana De Santiago,Santiago,1.0,10510,7010
999999,202308,101308,Atención Médica,Consulta Médica,75861667,B,30 a 34 años,Mujer,Metropolitana De Santiago,La Florida,1.0,10510,7010

In [124]:
df_MLE_limpio['CODIGO_PRESTACIÓN'] = df_MLE_limpio['CODIGO_PRESTACIÓN'].astype(str)
nombre_codigos["CODIGO_PRESTACIÓN"] = nombre_codigos["CODIGO_PRESTACIÓN"].astype(str)

df_MLE_limpio = df_MLE_limpio.merge(nombre_codigos, left_on="CODIGO_PRESTACIÓN", right_on="CODIGO_PRESTACIÓN", how='left')

C:\Users\benja\AppData\Local\Temp\ipykernel_11456\142898981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nombre_codigos["CODIGO_PRESTACIÓN"] = nombre_codigos["CODIGO_PRESTACIÓN"].astype(str)

In [125]:
df_MLE_limpio.sample(5)

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO,NOMBRE_PRESTACIÓN
401089,202307,601105,Otros Profesionales,Kinesiología,79406427,B,75 a 79 años,Mujer,Del Libertador General Bernardo O'Higgins,Rancagua,10.0,32400,71400,ATENCION KINESIOLOGICA INTEGRAL AMBULATORIA ...
567124,202303,1201016,Proc. Apoyo Clínico Y Terap.,Oftalmología,75058965,D,50 a 54 años,Mujer,De La Araucanía,Temuco,2.0,13100,28820,"ANGIOGRAFIA DE RETINA O DE IRIS, (CON FLUORESC..."
956998,202305,101001,Atención Médica,Consulta Médica,68519674,B,55 a 59 años,Mujer,De Valparaíso,Valparaíso,1.0,6600,7180,CONSULTA MEDICINA GENERAL ...
558912,202308,1801001,Proc. Apoyo Clínico Y Terap.,Gastroentorología,68353632,B,70 a 74 años,Hombre,Del Maule,Curicó,1.0,18580,40880,GASTRODUODENOSCOPIA (INCLUYE ESOFAGOSCOPIA) ...
854361,202309,307011,Exámenes De Diagnóstico,Laboratorio Clínico,80922220,C,70 a 74 años,Mujer,Metropolitana De Santiago,Independencia,1.0,410,410,VENOSA EN ADULTOS ...

In [126]:
#guardaremos el dataframe limpio en un archivo csv
if original2 == True:
    df_MLE_limpio.to_csv("../data/MLE_2023_original_limpio.csv", encoding='latin1', index=False)
elif original2 == False:
    df_MLE_limpio.to_csv("../data/sample/MLE_2023_sample_limpio.csv", encoding='latin1', index=False)

In [127]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO,NOMBRE_PRESTACIÓN
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900,"ORINA COMPLETA, (INCLUYE COD. 03-09-023 Y 03-0..."
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390,CREATININA EN SANGRE ...
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390,CREATININA EN SANGRE ...
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390,CREATININA EN SANGRE ...
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390,CREATININA EN SANGRE ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997524,202308,101301,Atención Médica,Consulta Médica,82181868,B,60 a 64 años,Hombre,Metropolitana De Santiago,San Bernardo,1.0,10510,7010,CONSULTA MEDICA DE ESPECIALIDAD EN CARDIOLOGIA...
997525,202308,101301,Atención Médica,Consulta Médica,69072699,C,60 a 64 años,Mujer,De Tarapacá,Iquique,1.0,10510,7010,CONSULTA MEDICA DE ESPECIALIDAD EN CARDIOLOGIA...
997526,202308,101308,Atención Médica,Consulta Médica,75587862,D,30 a 34 años,Mujer,De Los Lagos,Osorno,1.0,10510,7010,CONSULTA MEDICA DE ESPECIALIDAD EN OBSTETRICIA...
997527,202308,101308,Atención Médica,Consulta Médica,85032515,B,30 a 34 años,Mujer,Metropolitana De Santiago,Santiago,1.0,10510,7010,CONSULTA MEDICA DE ESPECIALIDAD EN OBSTETRICIA...
997528,202308,101308,Atención Médica,Consulta Médica,75861667,B,30 a 34 años,Mujer,Metropolitana De Santiago,La Florida,1.0,10510,7010,CONSULTA MEDICA DE ESPECIALIDAD EN OBSTETRICIA...