In [35]:
import pandas as pd

## Primer dataset - Beneficiarios FONASA 2023

In [ ]:
original1 = False
try:
    with open("../data/originales/Beneficiarios Fonasa 2023.csv", encoding="latin1", errors="ignore") as f:
        df_beneficiarios = pd.read_csv(f, nrows=1000000)
        print("Se cargo la muestra original")
        original1 = True
        # De tener dataset original, indica numero de filas a cargar o quitar nrows para carga completa

except FileNotFoundError:
    print("El archivo original no se encuentra, abriremos muestra") # Muestra de 100000 filas, habilitado para subir a github
    df_beneficiarios = pd.read_csv("../data/sample/beneficiarios_sample.csv", encoding='latin1')
    print("Se cargo la muestra")

El archivo original no se encuentra, abriremos muestra
Se cargo la muestra

In [37]:
df_beneficiarios

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,202312,77002490,Hombre,50 a 59 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Lo Espejo
99996,202312,71958114,Mujer,50 a 59 años,Titular,B,700.001 - 750.000,Chilena,Trabajador A Honorario,Trabajador Independiente,Del Libertador General Bernardo O'Higgins,Machalí
99997,202312,68992350,Mujer,50 a 59 años,Titular,B,300.001 - 350.000,Chilena,Dependiente,Trabajador Dependiente,Del Libertador General Bernardo O'Higgins,Quinta De Tilcoco
99998,202312,71182060,Mujer,50 a 59 años,Titular,B,600.001 - 650.000,Chilena,Trabajador A Honorario,Trabajador Independiente,De Los Lagos,Purranque
99999,202312,67045721,Mujer,50 a 59 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Melipilla

In [38]:
#revisar si tiene valores nulos
df_beneficiarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   MES_INFORMACION      100000 non-null  int64
 1   CÓDIGO_BENEFICIARIO  100000 non-null  int64
 2   SEXO                 100000 non-null  object
 3   EDAD_TRAMO           100000 non-null  object
 4   TITULAR_CARGA        100000 non-null  object
 5   TRAMO_FONASA         100000 non-null  object
 6   TRAMO_RENTA          100000 non-null  object
 7   NACIONALIDAD         100000 non-null  object
 8   CARACTERIZACIÓN      100000 non-null  object
 9   TIPO_ASEGURADO       100000 non-null  object
 10  REGIÓN_BENEFICIARIO  100000 non-null  object
 11  COMUNA_BENEFICIARIO  100000 non-null  object
dtypes: int64(2), object(10)
memory usage: 9.2+ MB

In [39]:
#eliminar las filas con valores nulos
df_beneficiarios_sin_nulos= df_beneficiarios.dropna()
df_beneficiarios_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   MES_INFORMACION      100000 non-null  int64
 1   CÓDIGO_BENEFICIARIO  100000 non-null  int64
 2   SEXO                 100000 non-null  object
 3   EDAD_TRAMO           100000 non-null  object
 4   TITULAR_CARGA        100000 non-null  object
 5   TRAMO_FONASA         100000 non-null  object
 6   TRAMO_RENTA          100000 non-null  object
 7   NACIONALIDAD         100000 non-null  object
 8   CARACTERIZACIÓN      100000 non-null  object
 9   TIPO_ASEGURADO       100000 non-null  object
 10  REGIÓN_BENEFICIARIO  100000 non-null  object
 11  COMUNA_BENEFICIARIO  100000 non-null  object
dtypes: int64(2), object(10)
memory usage: 9.2+ MB

In [40]:
#verificar si existen valores duplicados
df_beneficiarios_sin_nulos.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [41]:
#eliminar las filas duplicadas
df_beneficiarios_limpio = df_beneficiarios_sin_nulos.drop_duplicates()
df_beneficiarios_limpio.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [42]:
df_beneficiarios_limpio

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,202312,77002490,Hombre,50 a 59 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Lo Espejo
99996,202312,71958114,Mujer,50 a 59 años,Titular,B,700.001 - 750.000,Chilena,Trabajador A Honorario,Trabajador Independiente,Del Libertador General Bernardo O'Higgins,Machalí
99997,202312,68992350,Mujer,50 a 59 años,Titular,B,300.001 - 350.000,Chilena,Dependiente,Trabajador Dependiente,Del Libertador General Bernardo O'Higgins,Quinta De Tilcoco
99998,202312,71182060,Mujer,50 a 59 años,Titular,B,600.001 - 650.000,Chilena,Trabajador A Honorario,Trabajador Independiente,De Los Lagos,Purranque
99999,202312,67045721,Mujer,50 a 59 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Melipilla

In [43]:
#guardaremos el dataframe limpio en un archivo csv
if original1 == True:
    df_beneficiarios_limpio.to_csv("../data/beneficiarios_original_limpio.csv", encoding='latin1', index=False)
elif original1 == False:
    df_beneficiarios_limpio.to_csv("../data/sample/beneficiarios_sample_limpio.csv", encoding='latin1', index=False)

## Segundo dataset - Modalidad Libre Elección 2023

In [ ]:
original2 = False
try:
    with open("../data/originales/export MLE 2023.csv", encoding="latin1", errors="ignore") as f:
        df_MLE = pd.read_csv(f, nrows=1000000)
        print("Se cargo la muestra original")
        original2 = True
        # De tener dataset original, indica numero de filas a cargar o quitar nrows para carga completa

except FileNotFoundError:
    print("El archivo original no se encuentra, abriremos muestra") # Muestra de 100000 filas, habilitado para subir a github
    df_MLE = pd.read_csv("../data/sample/export_MLE_sample.csv", encoding="latin1")
    print("Se cargo la muestra")

El archivo original no se encuentra, abriremos muestra
Se cargo la muestra

In [45]:
df_MLE.shape

(100000, 13)

In [46]:
df_MLE

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTRACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,202308,101202,Atención Médica,Consulta Médica,76391769,D,85 a 89 años,Mujer,De Valparaíso,Villa Alemana,1.0,9330,15550
99996,202308,101203,Atención Médica,Consulta Médica,75506267,D,85 a 89 años,Mujer,De Tarapacá,Arica,1.0,9330,15550
99997,202306,101209,Atención Médica,Consulta Médica,81255758,D,25 a 29 años,Mujer,De Los Ríos,Valdivia,1.0,9330,15550
99998,202306,101209,Atención Médica,Consulta Médica,78171390,D,40 a 44 años,Mujer,Del Maule,Curicó,1.0,9330,15550
99999,202306,101209,Atención Médica,Consulta Médica,74643652,B,30 a 34 años,Mujer,Metropolitana De Santiago,Providencia,1.0,9330,15550

In [47]:
df_MLE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   MES_EMISION          100000 non-null  int64
 1   CODIGO_PRESTACIÓN    100000 non-null  int64
 2   DESC_SECCION         100000 non-null  object
 3   DESC_ITEM            100000 non-null  object
 4   CODIGO_BENEFICIARIO  100000 non-null  int64
 5   TRAMO_FONASA         100000 non-null  object
 6   EDAD_TRAMO           100000 non-null  object
 7   SEXO                 100000 non-null  object
 8   REGION_EMISION       100000 non-null  object
 9   COMUNA_EMISION       100000 non-null  object
 10  PRESTRACIONES        99823 non-null   float64
 11  MONTO_FAM            100000 non-null  int64
 12  MONTO_COPAGO         100000 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 9.9+ MB

In [48]:
#revisar si tiene valores nulos
df_MLE.isnull().values.any()

np.True_

In [49]:
# ver cuantos valores nulos hay por columna
df_MLE.isnull().sum()

MES_EMISION              0
CODIGO_PRESTACIÓN        0
DESC_SECCION             0
DESC_ITEM                0
CODIGO_BENEFICIARIO      0
TRAMO_FONASA             0
EDAD_TRAMO               0
SEXO                     0
REGION_EMISION           0
COMUNA_EMISION           0
PRESTRACIONES          177
MONTO_FAM                0
MONTO_COPAGO             0
dtype: int64

In [50]:
#eliminar las filas con valores nulos
df_MLE_sin_nulos= df_MLE.dropna()
df_MLE_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99823 entries, 0 to 99999
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MES_EMISION          99823 non-null  int64
 1   CODIGO_PRESTACIÓN    99823 non-null  int64
 2   DESC_SECCION         99823 non-null  object
 3   DESC_ITEM            99823 non-null  object
 4   CODIGO_BENEFICIARIO  99823 non-null  int64
 5   TRAMO_FONASA         99823 non-null  object
 6   EDAD_TRAMO           99823 non-null  object
 7   SEXO                 99823 non-null  object
 8   REGION_EMISION       99823 non-null  object
 9   COMUNA_EMISION       99823 non-null  object
 10  PRESTRACIONES        99823 non-null  float64
 11  MONTO_FAM            99823 non-null  int64
 12  MONTO_COPAGO         99823 non-null  int64
dtypes: float64(1), int64(5), object(7)
memory usage: 10.7+ MB

In [51]:
#reviasr si existen valores duplicados
df_MLE_sin_nulos.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 99823, dtype: bool

In [52]:
# eliminar las filas duplicadas
df_MLE_limpio = df_MLE_sin_nulos.drop_duplicates()
df_MLE_limpio.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 99823, dtype: bool

In [53]:
df_MLE_limpio = df_MLE_limpio.rename(columns={'PRESTRACIONES': 'PRESTACIONES'})

In [54]:
df_MLE_limpio["REGION_EMISION"] = df_MLE_limpio["REGION_EMISION"].replace({"Ñuble": "De Ñuble"})

In [55]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,202308,101202,Atención Médica,Consulta Médica,76391769,D,85 a 89 años,Mujer,De Valparaíso,Villa Alemana,1.0,9330,15550
99996,202308,101203,Atención Médica,Consulta Médica,75506267,D,85 a 89 años,Mujer,De Tarapacá,Arica,1.0,9330,15550
99997,202306,101209,Atención Médica,Consulta Médica,81255758,D,25 a 29 años,Mujer,De Los Ríos,Valdivia,1.0,9330,15550
99998,202306,101209,Atención Médica,Consulta Médica,78171390,D,40 a 44 años,Mujer,Del Maule,Curicó,1.0,9330,15550
99999,202306,101209,Atención Médica,Consulta Médica,74643652,B,30 a 34 años,Mujer,Metropolitana De Santiago,Providencia,1.0,9330,15550

In [56]:
#guardaremos el dataframe limpio en un archivo csv
if original2 == True:
    df_MLE_limpio.to_csv("../data/MLE_2023_original_limpio.csv", encoding='latin1', index=False)
elif original2 == False:
    df_MLE_limpio.to_csv("../data/sample/MLE_2023_sample_limpio.csv", encoding='latin1', index=False)

## Tercer Dataframe - Presupuestos MLE 2023

In [57]:
codigos_df = pd.read_excel("../data/originales/2 Planilla MLE 2023.xlsx", engine='openpyxl')

In [58]:
# Eliminamos codigos repetidos
codigos_df = codigos_df[~codigos_df["total1"].isin([0])].copy()

# Formateamos codigos a GSSPPP
codigos_df["CODIGO_PRESTACIÓN"] = (
    codigos_df['grupo'].astype(str).str.zfill(1) +
    codigos_df['sub_grupo'].astype(str).str.zfill(2) +
    codigos_df['presta'].astype(str).str.zfill(3)
)
codigos_df = codigos_df.rename(columns={"glosa": "NOMBRE_PRESTACIÓN"})

nombre_codigos = codigos_df[["CODIGO_PRESTACIÓN", "NOMBRE_PRESTACIÓN"]]

In [59]:
print(nombre_codigos['CODIGO_PRESTACIÓN'].duplicated().sum())

0

In [60]:
codigos_df.sample(5)

,secuencia,grupo,sub_grupo,presta,corr,titulo,anes1,anesben1,anes2,anesben2,...,valcir21,valcir22,valcir23,valcir31,valcir32,valcir33,valcir41,valcir42,valcir43,CODIGO_PRESTACIÓN
722,723,3,6,112,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,306112
313,314,3,2,45,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,302045
3071,3072,19,1,6,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1901006
1478,1479,11,1,44,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1101044
1185,1186,5,1,121,0,5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,501121

In [61]:
codigos_df.to_csv("../data/Presupuestos_MLE_2023_original_limpio.csv", encoding='latin1', index=False)

**Hacemos merge df_MLE_limpio y nombre_codigos; y añadimos columna "NOMRE_PRESTACION" al df_MLE_limpio**

In [62]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,202308,101202,Atención Médica,Consulta Médica,76391769,D,85 a 89 años,Mujer,De Valparaíso,Villa Alemana,1.0,9330,15550
99996,202308,101203,Atención Médica,Consulta Médica,75506267,D,85 a 89 años,Mujer,De Tarapacá,Arica,1.0,9330,15550
99997,202306,101209,Atención Médica,Consulta Médica,81255758,D,25 a 29 años,Mujer,De Los Ríos,Valdivia,1.0,9330,15550
99998,202306,101209,Atención Médica,Consulta Médica,78171390,D,40 a 44 años,Mujer,Del Maule,Curicó,1.0,9330,15550
99999,202306,101209,Atención Médica,Consulta Médica,74643652,B,30 a 34 años,Mujer,Metropolitana De Santiago,Providencia,1.0,9330,15550

In [63]:
df_MLE_limpio['CODIGO_PRESTACIÓN'] = df_MLE_limpio['CODIGO_PRESTACIÓN'].astype(str)
nombre_codigos["CODIGO_PRESTACIÓN"] = nombre_codigos["CODIGO_PRESTACIÓN"].astype(str)

df_MLE_limpio = df_MLE_limpio.merge(nombre_codigos, left_on="CODIGO_PRESTACIÓN", right_on="CODIGO_PRESTACIÓN", how='left')

C:\Users\benja\AppData\Local\Temp\ipykernel_6440\142898981.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nombre_codigos["CODIGO_PRESTACIÓN"] = nombre_codigos["CODIGO_PRESTACIÓN"].astype(str)

In [64]:
df_MLE_limpio.sample(5)

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO,NOMBRE_PRESTACIÓN
58821,202311,101310,Atención Médica,Consulta Médica,74220995,D,15 a 19 años,Hombre,De Coquimbo,La Serena,2.0,21020,14020,CONSULTA MEDICA DE ESPECIALIDAD EN TRAUMATOLOG...
20402,202305,101001,Atención Médica,Consulta Médica,75279392,D,25 a 29 años,Mujer,Metropolitana De Santiago,San Miguel,1.0,6600,7180,CONSULTA MEDICINA GENERAL ...
43579,202306,404016,Exámenes De Diagnóstico,Imagenología,69093380,B,45 a 49 años,Mujer,Del Libertador General Bernardo O'Higgins,Santa Cruz,1.0,8750,19270,ECOGRAFIA PARTES BLANDAS O MUSCULOESQUELETICA ...
53991,202305,306011,Exámenes De Diagnóstico,Laboratorio Clínico,83446317,B,20 a 24 años,Mujer,De Valparaíso,Viña Del Mar,1.0,1730,3810,"UROCULTIVO, RECUENTO DE COLONIAS Y ANTIBIOGRAM..."
33523,202303,302076,Exámenes De Diagnóstico,Laboratorio Clínico,74522208,B,75 a 79 años,Mujer,De Los Ríos,Valdivia,1.0,4510,9920,PERFIL HEPATICO (INCLUYE TIEMPO DE PROTROMBINA...

In [65]:
#guardaremos el dataframe limpio en un archivo csv
if original2 == True:
    df_MLE_limpio.to_csv("../data/MLE_2023_original_limpio.csv", encoding='latin1', index=False)
elif original2 == False:
    df_MLE_limpio.to_csv("../data/sample/MLE_2023_sample_limpio.csv", encoding='latin1', index=False)

In [66]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIÓN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTACIONES,MONTO_FAM,MONTO_COPAGO,NOMBRE_PRESTACIÓN
0,202305,309022,Exámenes De Diagnóstico,Laboratorio Clínico,97481406,D,35 a 39 años,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900,"ORINA COMPLETA, (INCLUYE COD. 03-09-023 Y 03-0..."
1,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76712895,X,50 a 54 años,Hombre,De Tarapacá,Iquique,1.0,630,1390,CREATININA EN SANGRE ...
2,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,69353764,B,50 a 54 años,Mujer,Metropolitana De Santiago,San Joaquín,1.0,630,1390,CREATININA EN SANGRE ...
3,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,76007327,B,55 a 59 años,Mujer,Del Bíobío,Curanilahue,1.0,630,1390,CREATININA EN SANGRE ...
4,202305,302023,Exámenes De Diagnóstico,Laboratorio Clínico,81474165,B,55 a 59 años,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390,CREATININA EN SANGRE ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99818,202308,101202,Atención Médica,Consulta Médica,76391769,D,85 a 89 años,Mujer,De Valparaíso,Villa Alemana,1.0,9330,15550,CONSULTA MEDICA DE ESPECIALIDAD EN GERIATRIA ...
99819,202308,101203,Atención Médica,Consulta Médica,75506267,D,85 a 89 años,Mujer,De Tarapacá,Arica,1.0,9330,15550,CONSULTA MEDICA DE ESPECIALIDAD EN NEUROCIRUGI...
99820,202306,101209,Atención Médica,Consulta Médica,81255758,D,25 a 29 años,Mujer,De Los Ríos,Valdivia,1.0,9330,15550,CONSULTA MEDICA DE ESPECIALIDAD EN NEUROLOGIA ...
99821,202306,101209,Atención Médica,Consulta Médica,78171390,D,40 a 44 años,Mujer,Del Maule,Curicó,1.0,9330,15550,CONSULTA MEDICA DE ESPECIALIDAD EN NEUROLOGIA ...
99822,202306,101209,Atención Médica,Consulta Médica,74643652,B,30 a 34 años,Mujer,Metropolitana De Santiago,Providencia,1.0,9330,15550,CONSULTA MEDICA DE ESPECIALIDAD EN NEUROLOGIA ...