In [10]:
import pandas as pd

In [11]:
df_beneficiarios = pd.read_csv("../data/beneficiarios_sample.csv", encoding='latin1')
df_beneficiarios

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
95,202312,68400895,Hombre,40 a 49 años,Titular,B,800.001 - 850.000,Chilena,Empleado Del Sector Salud,Trabajador Dependiente,Metropolitana De Santiago,Maipú
96,202312,86602758,Mujer,30 a 39 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Peñaflor
97,202312,76736354,Mujer,30 a 39 años,Titular,B,350.001 - 400.000,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Estación Central
98,202312,69521217,Hombre,30 a 39 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Estación Central
99,202312,85022323,Hombre,30 a 39 años,Titular,D,850.001 - 900.000,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Padre Hurtado

In [12]:
#revisar si tiene valores nulos
df_beneficiarios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MES_INFORMACION      100 non-null    int64
 1   CÓDIGO_BENEFICIARIO  100 non-null    int64
 2   SEXO                 100 non-null    object
 3   EDAD_TRAMO           100 non-null    object
 4   TITULAR_CARGA        100 non-null    object
 5   TRAMO_FONASA         100 non-null    object
 6   TRAMO_RENTA          100 non-null    object
 7   NACIONALIDAD         100 non-null    object
 8   CARACTERIZACIÓN      100 non-null    object
 9   TIPO_ASEGURADO       100 non-null    object
 10  REGIÓN_BENEFICIARIO  100 non-null    object
 11  COMUNA_BENEFICIARIO  100 non-null    object
dtypes: int64(2), object(10)
memory usage: 9.5+ KB

In [13]:
#eliminar las filas con valores nulos
df_beneficiarios_sin_nulos= df_beneficiarios.dropna()
df_beneficiarios_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MES_INFORMACION      100 non-null    int64
 1   CÓDIGO_BENEFICIARIO  100 non-null    int64
 2   SEXO                 100 non-null    object
 3   EDAD_TRAMO           100 non-null    object
 4   TITULAR_CARGA        100 non-null    object
 5   TRAMO_FONASA         100 non-null    object
 6   TRAMO_RENTA          100 non-null    object
 7   NACIONALIDAD         100 non-null    object
 8   CARACTERIZACIÓN      100 non-null    object
 9   TIPO_ASEGURADO       100 non-null    object
 10  REGIÓN_BENEFICIARIO  100 non-null    object
 11  COMUNA_BENEFICIARIO  100 non-null    object
dtypes: int64(2), object(10)
memory usage: 9.5+ KB

In [14]:
#verificar si existen valores duplicados
df_beneficiarios_sin_nulos.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [15]:
#eliminar las filas duplicadas
df_beneficiarios_limpio = df_beneficiarios_sin_nulos.drop_duplicates()
df_beneficiarios_limpio.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [16]:
df_beneficiarios_limpio

,MES_INFORMACION,CÓDIGO_BENEFICIARIO,SEXO,EDAD_TRAMO,TITULAR_CARGA,TRAMO_FONASA,TRAMO_RENTA,NACIONALIDAD,CARACTERIZACIÓN,TIPO_ASEGURADO,REGIÓN_BENEFICIARIO,COMUNA_BENEFICIARIO
0,202312,71819187,Hombre,40 a 49 años,Titular,D,650.001 - 700.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Curanilahue
1,202312,80064014,Hombre,40 a 49 años,Titular,D,900.001 - 950.000,Chilena,Dependiente,Trabajador Dependiente,Del Bíobío,Concepción
2,202312,87503153,Mujer,50 a 59 años,Titular,A,Sin Cotizaciones,Chilena,Grupo Hogar Carente,Carente,De La Araucanía,Ercilla
3,202312,71657668,Mujer,40 a 49 años,Titular,A,Sin Cotizaciones,Chilena,Suf,Carente,De La Araucanía,Victoria
4,202312,75628648,Mujer,40 a 49 años,Titular,B,1 - 100.000,Chilena,Pensionado,Pensionado,De La Araucanía,Victoria
...,...,...,...,...,...,...,...,...,...,...,...,...
95,202312,68400895,Hombre,40 a 49 años,Titular,B,800.001 - 850.000,Chilena,Empleado Del Sector Salud,Trabajador Dependiente,Metropolitana De Santiago,Maipú
96,202312,86602758,Mujer,30 a 39 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Peñaflor
97,202312,76736354,Mujer,30 a 39 años,Titular,B,350.001 - 400.000,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Estación Central
98,202312,69521217,Hombre,30 a 39 años,Titular,C,Sin Cotizaciones,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Estación Central
99,202312,85022323,Hombre,30 a 39 años,Titular,D,850.001 - 900.000,Chilena,Dependiente,Trabajador Dependiente,Metropolitana De Santiago,Padre Hurtado

In [17]:
#guardaremos el dataframe limpio en un archivo csv
df_beneficiarios_limpio.to_csv("../data/beneficiarios_sample_limpio.csv", encoding='latin1', index=False)

In [18]:
with open("../data/export MLE 2023.csv",encoding="utf-8", errors="ignore") as f:
    df_MLE = pd.read_csv(f, nrows=6000000) #6 millones de datos

In [19]:
df_MLE.shape

(6000000, 13)

In [20]:
df_MLE

,MES_EMISION,CODIGO_PRESTACIN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTRACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exmenes De Diagnstico,Laboratorio Clnico,97481406,D,35 a 39 aos,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,76712895,X,50 a 54 aos,Hombre,De Tarapac,Iquique,1.0,630,1390
2,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,69353764,B,50 a 54 aos,Mujer,Metropolitana De Santiago,San Joaqun,1.0,630,1390
3,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,76007327,B,55 a 59 aos,Mujer,Del Bobo,Curanilahue,1.0,630,1390
4,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,81474165,B,55 a 59 aos,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5999995,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,72467778,D,60 a 64 aos,Hombre,De La Araucana,Temuco,1.0,2740,6040
5999996,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,81537908,B,70 a 74 aos,Mujer,De Coquimbo,Ovalle,1.0,2740,6040
5999997,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,78866768,B,65 a 69 aos,Hombre,De Coquimbo,Coquimbo,1.0,2740,6040
5999998,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,69752641,D,70 a 74 aos,Mujer,Del Maule,Molina,1.0,2740,6040
5999999,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,92197801,C,40 a 44 aos,Hombre,Metropolitana De Santiago,Recoleta,1.0,2740,6040

In [21]:
df_MLE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000000 entries, 0 to 5999999
Data columns (total 13 columns):
 #   Column               Dtype
---  ------               -----
 0   MES_EMISION          int64
 1   CODIGO_PRESTACIN     int64
 2   DESC_SECCION         object
 3   DESC_ITEM            object
 4   CODIGO_BENEFICIARIO  int64
 5   TRAMO_FONASA         object
 6   EDAD_TRAMO           object
 7   SEXO                 object
 8   REGION_EMISION       object
 9   COMUNA_EMISION       object
 10  PRESTRACIONES        float64
 11  MONTO_FAM            int64
 12  MONTO_COPAGO         int64
dtypes: float64(1), int64(5), object(7)
memory usage: 595.1+ MB

In [22]:
#revisar si tiene valores nulos
df_MLE.isnull().values.any()

True

In [23]:
# ver cuantos valores nulos hay por columna
df_MLE.isnull().sum()

MES_EMISION                0
CODIGO_PRESTACIN           0
DESC_SECCION               0
DESC_ITEM                  0
CODIGO_BENEFICIARIO        0
TRAMO_FONASA              15
EDAD_TRAMO                15
SEXO                      15
REGION_EMISION             5
COMUNA_EMISION             5
PRESTRACIONES          12811
MONTO_FAM                  0
MONTO_COPAGO               0
dtype: int64

In [24]:
#eliminar las filas con valores nulos
df_MLE_sin_nulos= df_MLE.dropna()
df_MLE_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5987169 entries, 0 to 5999999
Data columns (total 13 columns):
 #   Column               Dtype
---  ------               -----
 0   MES_EMISION          int64
 1   CODIGO_PRESTACIN     int64
 2   DESC_SECCION         object
 3   DESC_ITEM            object
 4   CODIGO_BENEFICIARIO  int64
 5   TRAMO_FONASA         object
 6   EDAD_TRAMO           object
 7   SEXO                 object
 8   REGION_EMISION       object
 9   COMUNA_EMISION       object
 10  PRESTRACIONES        float64
 11  MONTO_FAM            int64
 12  MONTO_COPAGO         int64
dtypes: float64(1), int64(5), object(7)
memory usage: 639.5+ MB

In [25]:
#reviasr si existen valores duplicados
df_MLE_sin_nulos.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
5999995    False
5999996    False
5999997    False
5999998    False
5999999    False
Length: 5987169, dtype: bool

In [26]:
# eliminar las filas duplicadas
df_MLE_limpio = df_MLE_sin_nulos.drop_duplicates()
df_MLE_limpio.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
5999995    False
5999996    False
5999997    False
5999998    False
5999999    False
Length: 5987169, dtype: bool

In [27]:
df_MLE_limpio

,MES_EMISION,CODIGO_PRESTACIN,DESC_SECCION,DESC_ITEM,CODIGO_BENEFICIARIO,TRAMO_FONASA,EDAD_TRAMO,SEXO,REGION_EMISION,COMUNA_EMISION,PRESTRACIONES,MONTO_FAM,MONTO_COPAGO
0,202305,309022,Exmenes De Diagnstico,Laboratorio Clnico,97481406,D,35 a 39 aos,Mujer,Metropolitana De Santiago,La Cisterna,1.0,890,900
1,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,76712895,X,50 a 54 aos,Hombre,De Tarapac,Iquique,1.0,630,1390
2,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,69353764,B,50 a 54 aos,Mujer,Metropolitana De Santiago,San Joaqun,1.0,630,1390
3,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,76007327,B,55 a 59 aos,Mujer,Del Bobo,Curanilahue,1.0,630,1390
4,202305,302023,Exmenes De Diagnstico,Laboratorio Clnico,81474165,B,55 a 59 aos,Mujer,Metropolitana De Santiago,Las Condes,1.0,630,1390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5999995,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,72467778,D,60 a 64 aos,Hombre,De La Araucana,Temuco,1.0,2740,6040
5999996,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,81537908,B,70 a 74 aos,Mujer,De Coquimbo,Ovalle,1.0,2740,6040
5999997,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,78866768,B,65 a 69 aos,Hombre,De Coquimbo,Coquimbo,1.0,2740,6040
5999998,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,69752641,D,70 a 74 aos,Mujer,Del Maule,Molina,1.0,2740,6040
5999999,202303,302034,Exmenes De Diagnstico,Laboratorio Clnico,92197801,C,40 a 44 aos,Hombre,Metropolitana De Santiago,Recoleta,1.0,2740,6040

In [28]:
#guardaremos el dataframe limpio en un archivo csv
df_beneficiarios_limpio.to_csv("../data/export MLE 2023 limpio.csv", encoding='latin1', index=False)